feat: [ENG-1360] Add AdminClient to pubsubx (#49)
* Add admin client to pubsub

* Add format cmd

* Fix mocks

* Return admin client

* Use dedicated health check method instead

* Fix inmemory client

* Return new adminclient instance

* Makefile fix

* Add debug log

* Add poll for slow kafka responses

* Add teardown to ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,6 +44,20 @@ jobs:
           check-latest: true
           cache: true
       
+      - name: Install gofumpt
+        run: make install
+
+      - name: Check format
+        run: |
+          format_output=$(gofumpt -l .)
+          if [ "$format_output" = "" ]; then
+            echo "✅ All files are formatted correctly."
+            exit 0
+          else
+            echo "::error::The following files are not formatted correctly: $format_output"
+            exit 1
+          fi
+
       - name: Lint
         uses: golangci/golangci-lint-action@v6
         with:
